### ISSUE TITLE
Using ground truth test triples for choosing negative sample during test

### ISSUE THREAD

**Issue by ZifengDing** [AnselCmy/MetaR#10]
Hi,

I notice that when you compute relation meta during test, you exclude the ground truth test triples during negative sample, which means that you are already somehow using ground truth information before you compute the link scores.
Is this allowed? How to understand this step?
I understand you need to update relation meta during evaluation, but using ground truth triple information would cause information leak, right?

**Comment by AnselCmy** [comment]
Hi, thanks for your contact! During the evaluation, we calculate the relation meta based on the support triples and their sampled negative triples. Since in the few-shot link prediction setting, ground truth triples in the support sets are visible for models, and we are allowed to know the ground truth triples. Furthermore, we can use the information on ground truth triples in the support sets to model "more real negative triples" by excluding the ground truth triples in the support sets. Note that, during the negative sampling in the support sets, we only use the ground truth information in the support set but not the query set, so we don't leak any information about link prediction in the query set.
